[pytest]
# Configuração da URL Base para evitar repetições no código
base_url = https://blogdoagi.com.br

# Configurações padrão de execução
addopts = --browser chromium --html=report.html --self-contained-html -v

# Identificação das pastas de testes
testpaths = testes
